"""Initial

Revision ID: b22292447051
Revises: ead288479eee
Create Date: 2023-08-14 14:28:14.932001

"""

from utils.initial_data import database_initialization
# revision identifiers, used by Alembic.
revision = 'b22292447051'
down_revision = 'ead288479eee'
branch_labels = None
depends_on = None


def upgrade() -> None:

    users = [
        {'name':'Кожурин Сергей Сергеевич', 'email':'q', 'password':'q'},
        {'name':'Шляпников Гурий Александрович', 'email':'q', 'password':'q'},
        {'name':'Астахова Анна Евгеньевна', 'email':'q', 'password':'q'},
        {'name':'Мотузов Фёдор Сергеевич', 'email':'q', 'password':'q'},
        {'name':'Афонин Алексей Геннадьевич', 'email':'q', 'password':'q'},
        {'name':'Емелькин Василий Анатольевич', 'email':'q', 'password':'q'},
        {'name':'Устименко Марина Николаевна', 'email':'q', 'password':'q'}
        # Add more users as needed
    ]

    for user in users:
        
        database_initialization(user)

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
